-- 1. Tambahkan kolom ID (Auto Increment)
ALTER TABLE master_siswa 
ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;

-- 2. (Opsional) Menjadikan ID sebagai Primary Key
-- Hati-hati: Ini akan menghapus Primary Key NISN yang lama.
-- Pastikan tidak ada tabel lain yang mereferensi NISN sebagai Foreign Key sebelum menjalankan ini,
-- ATAU pastikan relasi tersebut diperbarui.

-- ALTER TABLE master_siswa DROP CONSTRAINT master_siswa_pkey;
-- ALTER TABLE master_siswa ADD PRIMARY KEY (id);

-- 3. (Opsional) Menambahkan batasan Unik pada NISN (jika NISN bukan lagi PK)
-- ALTER TABLE master_siswa ADD CONSTRAINT master_siswa_nisn_key UNIQUE (nisn);
