-- Migration Script: Reorder master_siswa columns (Move ID to first position)
-- Run this in Supabase SQL Editor

BEGIN;

-- 1. Drop Dependencies (Foreign Keys) temporarily if they exist
-- We use IF EXISTS to prevent errors if the constraint is named differently
ALTER TABLE IF EXISTS siswa_kelas 
DROP CONSTRAINT IF EXISTS siswa_kelas_nisn_fkey;

ALTER TABLE IF EXISTS nilai_siswa 
DROP CONSTRAINT IF EXISTS nilai_siswa_nisn_fkey;

-- 2. Create New Table with desired column order
CREATE TABLE master_siswa_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- First Position
    nisn text NOT NULL,
    nama_lengkap text,
    gender text,
    tempat_lahir text,
    tanggal_lahir date,
    nama_ayah text,
    nama_ibu text,
    nomor_hp_ayah text,
    nomor_hp_ibu text,
    alamat text,
    asal_sekolah text,
    aktif boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz
);

-- 3. Copy Data from Old Table
INSERT INTO master_siswa_new (
    id, nisn, nama_lengkap, gender, tempat_lahir, tanggal_lahir, 
    nama_ayah, nama_ibu, nomor_hp_ayah, nomor_hp_ibu, alamat, 
    asal_sekolah, aktif, created_at, updated_at
)
SELECT 
    id, nisn, nama_lengkap, gender, tempat_lahir, tanggal_lahir, 
    nama_ayah, nama_ibu, nomor_hp_ayah, nomor_hp_ibu, alamat, 
    asal_sekolah, aktif, created_at, updated_at 
FROM master_siswa;

-- 4. Drop Old Table
DROP TABLE master_siswa;

-- 5. Rename New Table
ALTER TABLE master_siswa_new RENAME TO master_siswa;

-- 6. Add Constraints
ALTER TABLE master_siswa ADD CONSTRAINT master_siswa_nisn_key UNIQUE (nisn);

-- 7. Restore Foreign Keys (linking back to NISN for compatibility with current App)
-- Note: Ideally FK should point to ID, but our App currently uses NISN for relations.
-- If siswa_kelas table exists, re-add constraint:
DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'siswa_kelas') THEN
        ALTER TABLE siswa_kelas 
        ADD CONSTRAINT siswa_kelas_nisn_fkey 
        FOREIGN KEY (nisn) REFERENCES master_siswa(nisn) 
        ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

COMMIT;
