-- Migration Script: Reorder master_guru columns (Add ID as Primary Key)
-- Run this in Supabase SQL Editor

BEGIN;

-- 1. Drop Dependencies (Foreign Keys) temporarily
-- Check tables that might reference master_guru(nip)
ALTER TABLE IF EXISTS guru_mapel 
DROP CONSTRAINT IF EXISTS guru_mapel_nip_fkey;

ALTER TABLE IF EXISTS guru_asuh 
DROP CONSTRAINT IF EXISTS guru_asuh_nip_fkey;

ALTER TABLE IF EXISTS jadwal_pelajaran 
DROP CONSTRAINT IF EXISTS jadwal_pelajaran_guru_nip_fkey;

-- 2. Create New Table with ID first
CREATE TABLE master_guru_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- First Position
    nip text NOT NULL,
    nama_lengkap text,
    tempat_lahir text,
    tanggal_lahir date,
    golongan text,
    pangkat text,
    tmt_tugas date,
    riwayat_pendidikan jsonb, -- Assuming json/jsonb
    alamat text,
    email text,
    no_hp text,
    aktif boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz
);

-- 3. Copy Data
INSERT INTO master_guru_new (
    nip, nama_lengkap, tempat_lahir, tanggal_lahir, 
    golongan, pangkat, tmt_tugas, riwayat_pendidikan, 
    alamat, email, no_hp, aktif, created_at, updated_at
)
SELECT 
    nip, nama_lengkap, tempat_lahir, tanggal_lahir, 
    golongan, pangkat, tmt_tugas, riwayat_pendidikan, 
    alamat, email, no_hp, aktif, created_at, updated_at
FROM master_guru;

-- 4. Swap Tables
DROP TABLE master_guru;
ALTER TABLE master_guru_new RENAME TO master_guru;

-- 5. Add Unique Constraint on NIP (since it's still used for relations)
ALTER TABLE master_guru ADD CONSTRAINT master_guru_nip_key UNIQUE (nip);

-- 6. Restore Foreign Keys (linking back to NIP for compatibility)
DO $$
BEGIN
    -- Restore guru_mapel FK
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'guru_mapel') THEN
        ALTER TABLE guru_mapel 
        ADD CONSTRAINT guru_mapel_nip_fkey 
        FOREIGN KEY (nip) REFERENCES master_guru(nip) 
        ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;

    -- Restore guru_asuh FK
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'guru_asuh') THEN
        ALTER TABLE guru_asuh 
        ADD CONSTRAINT guru_asuh_nip_fkey 
        FOREIGN KEY (nip) REFERENCES master_guru(nip) 
        ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

COMMIT;
